"""
APEX Report Generator - compiles findings into a pentest-style report.

Phase 7: Markdown and a self-contained HTML version, built from either an
in-memory apex.orchestrator.AssessmentResult or the dict
apex.storage.load_assessment() returns - so a report can be generated right
after a live run, or later from persisted history. No PDF/DOCX dependency
and no report-styling framework; simple string templating is enough for
this prototype (see README "Design Notes").

Run standalone: python -m apex.report
"""

from datetime import datetime, timezone

_SEVERITY_ORDER = ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"]


def _severity_counts(findings: list[dict]) -> dict[str, int]:
    counts: dict[str, int] = {}
    for f in findings:
        counts[f["severity"]] = counts.get(f["severity"], 0) + 1
    return counts


def _as_finding_dicts(findings) -> list[dict]:
    """Findings may be apex.findings.Finding objects (in-memory) or plain
    dicts (loaded back from storage) - normalize to dicts either way."""
    normalized = []
    for f in findings:
        if isinstance(f, dict):
            normalized.append(f)
        else:
            normalized.append(
                {
                    "title": f.title,
                    "attack_type": f.attack_type,
                    "severity": f.severity.value,
                    "description": f.description,
                    "evidence": f.evidence,
                    "payload": f.payload,
                    "target": f.target,
                    "classification": f.classification.value,
                    "recommendation": f.recommendation,
                    "timestamp": f.timestamp,
                }
            )
    return normalized


def _profile_lines(profile) -> list[str]:
    if profile is None:
        return ["No recon profile available."]
    if not isinstance(profile, dict):
        profile = profile.to_dict()
    lines = [
        f"RAG: {'detected' if profile.get('rag_detected') else 'not detected'}",
        f"File Reader: {'detected' if profile.get('file_reader_detected') else 'not detected'}",
        f"Database Tool: {'detected' if profile.get('database_tool_detected') else 'not detected'}",
        f"Email Tool: {'detected' if profile.get('email_tool_detected') else 'not detected'}",
    ]
    if profile.get("knowledge_topics"):
        lines.append(f"Knowledge topics: {', '.join(profile['knowledge_topics'])}")
    if profile.get("attack_surfaces"):
        lines.append(f"Potential attack surfaces: {', '.join(profile['attack_surfaces'])}")
    return lines


def _unpack(result) -> dict:
    is_dict = isinstance(result, dict)
    if is_dict:
        attempts = result.get("attempts", [])
    else:
        attempts = getattr(result, "attempts", [])
    return {
        "target_name": result["target_name"] if is_dict else result.target_name,
        "started_at": result["started_at"] if is_dict else result.started_at,
        "finished_at": result["finished_at"] if is_dict else result.finished_at,
        "status": result["status"] if is_dict else result.status,
        "profile": result["target_profile"] if is_dict else result.target_profile,
        "findings": _as_finding_dicts(result["findings"] if is_dict else result.findings),
        # `attempts` may be absent on assessments persisted before the
        # payload-library expansion added attempt-level logging - .get()
        # above and this default keep older reports rendering fine.
        "attempts": attempts,
    }


_LIMITATIONS_TEXT = (
    "This report was generated by a scoped prototype, not the full APEX FYP system. Classification is "
    "rule-based (not an ML/LLM judge), the target is a self-built simulated agent (VICTIM), and no adaptive "
    "attack chaining, benchmark evaluation, or knowledge-base exfiltration/action-abuse modules are "
    "included. See the project README for full scope and the future roadmap."
)


def generate_markdown_report(result) -> str:
    data = _unpack(result)
    counts = _severity_counts(data["findings"])
    generated_at = datetime.now(timezone.utc).isoformat()
    status = data["status"]
    status_label = status.title() if isinstance(status, str) else status

    lines = [
        "# APEX Security Assessment Report",
        "",
        f"**Target:** {data['target_name']}  ",
        f"**Assessment started:** {data['started_at']}  ",
        f"**Assessment finished:** {data['finished_at'] or '-'}  ",
        f"**Status:** {status_label}  ",
        f"**Report generated:** {generated_at}",
        "",
        "## Discovered Capabilities",
        "",
    ]
    lines += [f"- {line}" for line in _profile_lines(data["profile"])]
    lines += ["", "## Summary", "", f"**Total findings:** {len(data['findings'])}", ""]

    for severity in _SEVERITY_ORDER:
        if counts.get(severity):
            lines.append(f"- **{severity}:** {counts[severity]}")
    if not data["findings"]:
        lines.append("- No findings — the target resisted every attack in this assessment.")

    if data["attempts"]:
        resisted = sum(1 for a in data["attempts"] if a.get("classification") == "SAFE")
        lines.append(
            f"- **Attempts:** {len(data['attempts'])} total ({resisted} resisted, classified SAFE)"
        )

    lines += ["", "## Findings", ""]

    if not data["findings"]:
        lines.append("_No findings to report._")
    else:
        ordered = sorted(
            data["findings"],
            key=lambda f: _SEVERITY_ORDER.index(f["severity"]) if f["severity"] in _SEVERITY_ORDER else 99,
        )
        for i, f in enumerate(ordered, start=1):
            lines += [
                f"### {i}. [{f['severity']}] {f['title']}",
                "",
                f"- **Attack type:** `{f['attack_type']}`",
                f"- **Classification:** `{f['classification']}`",
                f"- **Target:** {f['target']}",
                f"- **Timestamp:** {f['timestamp']}",
                "",
                "**Description:**",
                "",
                f"{f['description']}",
                "",
                "**Payload:**",
                "",
                "```",
                f"{f['payload']}",
                "```",
                "",
                "**Evidence:**",
                "",
                "```",
                f"{f['evidence']}",
                "```",
                "",
                "**Recommendation:**",
                "",
                f"{f['recommendation']}",
                "",
                "---",
                "",
            ]

    lines += ["## Limitations", "", _LIMITATIONS_TEXT]
    return "\n".join(lines)


def generate_html_report(result) -> str:
    data = _unpack(result)
    counts = _severity_counts(data["findings"])
    generated_at = datetime.now(timezone.utc).isoformat()
    status = data["status"]
    status_label = status.title() if isinstance(status, str) else status

    def esc(value) -> str:
        return str(value).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")

    severity_colors = {
        "CRITICAL": "#b91c1c",
        "HIGH": "#c2410c",
        "MEDIUM": "#a16207",
        "LOW": "#1d4ed8",
        "INFO": "#374151",
    }

    profile_html = "".join(f"<li>{esc(line)}</li>" for line in _profile_lines(data["profile"]))

    summary_html = "".join(
        f'<li><strong style="color:{severity_colors.get(sev, "#000")}">{sev}</strong>: {counts[sev]}</li>'
        for sev in _SEVERITY_ORDER
        if counts.get(sev)
    ) or "<li>No findings — the target resisted every attack in this assessment.</li>"

    if data["attempts"]:
        resisted = sum(1 for a in data["attempts"] if a.get("classification") == "SAFE")
        summary_html += (
            f"<li><strong>Attempts:</strong> {len(data['attempts'])} total "
            f"({resisted} resisted, classified SAFE)</li>"
        )

    ordered = sorted(
        data["findings"],
        key=lambda f: _SEVERITY_ORDER.index(f["severity"]) if f["severity"] in _SEVERITY_ORDER else 99,
    )

    findings_html = ""
    for i, f in enumerate(ordered, start=1):
        color = severity_colors.get(f["severity"], "#000")
        findings_html += f"""
        <div style="border:1px solid #ddd; border-radius:8px; padding:16px; margin-bottom:16px;">
          <h3 style="margin-top:0;"><span style="color:{color};">[{esc(f['severity'])}]</span> {i}. {esc(f['title'])}</h3>
          <p><strong>Attack type:</strong> <code>{esc(f['attack_type'])}</code> &nbsp;
             <strong>Classification:</strong> <code>{esc(f['classification'])}</code></p>
          <p><strong>Description:</strong> {esc(f['description'])}</p>
          <p><strong>Payload:</strong></p>
          <pre style="background:#f5f5f5; padding:8px; white-space:pre-wrap;">{esc(f['payload'])}</pre>
          <p><strong>Evidence:</strong></p>
          <pre style="background:#f5f5f5; padding:8px; white-space:pre-wrap;">{esc(f['evidence'])}</pre>
          <p><strong>Recommendation:</strong> {esc(f['recommendation'])}</p>
        </div>
        """

    if not data["findings"]:
        findings_html = "<p><em>No findings to report.</em></p>"

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>APEX Security Assessment Report — {esc(data['target_name'])}</title>
</head>
<body style="font-family: -apple-system, Segoe UI, Arial, sans-serif; max-width: 900px; margin: 40px auto; padding: 0 16px; color:#111;">
  <h1>APEX Security Assessment Report</h1>
  <p><strong>Target:</strong> {esc(data['target_name'])}<br>
     <strong>Assessment started:</strong> {esc(data['started_at'])}<br>
     <strong>Assessment finished:</strong> {esc(data['finished_at'] or '-')}<br>
     <strong>Status:</strong> {esc(status_label)}<br>
     <strong>Report generated:</strong> {esc(generated_at)}</p>

  <h2>Discovered Capabilities</h2>
  <ul>{profile_html}</ul>

  <h2>Summary</h2>
  <p><strong>Total findings:</strong> {len(data['findings'])}</p>
  <ul>{summary_html}</ul>

  <h2>Findings</h2>
  {findings_html}

  <h2>Limitations</h2>
  <p>{esc(_LIMITATIONS_TEXT)}</p>
</body>
</html>
"""


if __name__ == "__main__":
    import sys
    from pathlib import Path

    sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

    from apex import storage
    from apex.connector import LocalVictimConnector
    from apex.orchestrator import run_assessment

    connector = LocalVictimConnector()
    result = run_assessment(connector)
    assessment_id = storage.save_assessment(result)

    out_dir = Path(__file__).resolve().parent.parent / "reports"
    out_dir.mkdir(exist_ok=True)
    md_path = out_dir / f"apex_report_{assessment_id}.md"
    html_path = out_dir / f"apex_report_{assessment_id}.html"
    md_path.write_text(generate_markdown_report(result), encoding="utf-8")
    html_path.write_text(generate_html_report(result), encoding="utf-8")

    print(f"Assessment #{assessment_id} saved to SQLite ({len(result.findings)} findings).")
    print(f"Markdown report: {md_path}")
    print(f"HTML report:     {html_path}")
